Shemshey maxim dao task
ShemsheyMaxim/jv-create-annotation pull request #1
Opened 2021-01-08 00:37 UTC by ShemsheyMaxim

2021-01-08 07:58 UTC, NikolayFatkullin approved these changes

2021-01-08 13:02 UTC, dmytro-hryhoruk requested changes

2021-01-08 13:02 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandlerImpl.java
> +    private final BetDao betDao = new BetDaoImpl();
other Dao?

2021-01-08 13:02 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandlerImpl.java
> +                        + "сумму(число) и коеффициент(число) через пробел для для вашей ставки");
Let's write in English)

2021-01-08 13:02 UTC, dmytro-hryhoruk commented on src/main/java/core/basesyntax/controller/ConsoleHandlerImpl.java
> +                    + "чтобы завершить работу");
Let's pring all bets using getAll() after loop

2021-01-08 16:41 UTC, ShemsheyMaxim commented on src/main/java/core/basesyntax/controller/ConsoleHandlerImpl.java
> +    private final BetDao betDao = new BetDaoImpl();
done

2021-01-08 16:41 UTC, ShemsheyMaxim commented on src/main/java/core/basesyntax/controller/ConsoleHandlerImpl.java
> +                        + "сумму(число) и коеффициент(число) через пробел для для вашей ставки");
done

2021-01-08 16:41 UTC, ShemsheyMaxim commented on src/main/java/core/basesyntax/controller/ConsoleHandlerImpl.java
> +                    + "чтобы завершить работу");
done

2021-01-08 18:24 UTC, dmytro-hryhoruk approved these changes

2021-01-10 22:57 UTC, ShemsheyMaxim commented
I forgot merge pull request after first part.

2021-01-11 07:32 UTC, Fedich09 approved these changes

2021-01-11 08:37 UTC, RomanDubovskyi commented
you have files from prev hw, they should not be in this PR, fix it before review

2021-01-11 12:41 UTC, merged